
# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# Stabilize first
pull_requests:
  do_not_increment_build_number: true

# Maximum number of concurrent jobs for the project
max_jobs: 2

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# clone directory
clone_folder: c:\projects\ElunaTrinityWotlk

# set clone depth
clone_depth: 1                      # clone entire repository history if not defined

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# build Configuration, i.e. Debug, Release, etc.
configuration: RelWithDebInfo

# Build settings, not to be confused with "before_build" and "after_build".
# "project" is relative to the original build directory and not influenced by directory changes in "before_build".
build:
  parallel: true                  # enable MSBuild parallel builds
  project: TrinityCore.sln        # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: minimal

addons:
  apt:
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
#     - sourceline: 'ubuntu-toolchain-r-test'
    packages:
      - boost1.67
      - libssl-dev
      - libmysqlclient-dev
      - libreadline6-dev
      - zlib1g-dev
      - libbz2-dev
      - g++-6

# scripts to run before build
before_build:
  - git config user.email "appveyor@build.bot" && git config user.name "AppVeyor"
  - git tag -a -m "AppVeyor build" init
  - md build && cd build
  - cmake -G"Visual Studio 15 2017 Win64" -DSCRIPTS=dynamic -DTOOLS=True -DCMAKE_CXX_FLAGS=" /DWIN32 /D_WINDOWS /W3 /GR /EHsc /WX" -DCMAKE_C_FLAGS="/DWIN32 /D_WINDOWS /W3 /WX" ..

# to run your custom scripts instead of automatic MSBuild
build_script:

# scripts to run after build (working directory and environment changes are persisted from the previous steps)
after_build:
  - cd bin\RelWithDebInfo\
  - copy "C:\Program Files\MySQL\MySQL Server 5.7\lib\libmysql.dll" libmysql.dll
  - copy "%OPENSSL_ROOT_DIR%\ssleay32.dll" ssleay32.dll
  - copy "%OPENSSL_ROOT_DIR%\libeay32.dll" libeay32.dll

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
before_package:


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  # pushing a single file
  - path: ElunaTrinityWotlkWin64VS2017.zip
