# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#
# version format
version: 1.0.{build}

# set clone depth
clone_depth: 1                      # clone entire repository history if not defined

# fetch repository as zip archive
shallow_clone: true

# clone script - use of --recursive for LuaEngine
clone_script:
  - cmd: git clone -q --recursive --depth=1 --branch=master https://github.com/RedSkull-666/ElunaTrinityWotlk.git C:\projects\ElunaTrinityWotlk

init:
- ps: ''

#---------------------------------#
#    environment configuration    #
#---------------------------------#
# Build worker image (VM template)
image: Visual Studio 2019

# environment variables
environment:
  CMAKE_GENERATOR: "Visual Studio 16 2019 Win64"
  BOOST_ROOT: C:\Libraries\boost_1_71_0
  BOOST_INCLUDEDIR: C:\Libraries\boost_1_71_0\boost
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_71_0\lib64-msvc-14.1
  OPENSSL_ROOT_DIR: C:\OpenSSL-Win64

#---------------------------------#
#       build configuration       #
#---------------------------------#
# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# build Configuration, i.e. Debug, Release, etc.
configuration: RelWithDebInfo

# Build settings, not to be confused with "before_build" and "after_build".
# "project" is relative to the original build directory and not influenced by directory changes in "before_build".
build:
  parallel: true                  # enable MSBuild parallel builds
  project: TrinityCore.sln        # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: minimal

build_script:
- cmd: >-
    git config user.email "appveyor@build.bot" && git config user.name "AppVeyor"

    git tag -a -m "AppVeyor build" init

    md build && cd build

    cmake -G"Visual Studio 16 2019" -A x64 -DSCRIPTS=dynamic -DTOOLS=True -DCMAKE_CXX_FLAGS=" /DWIN32 /D_WINDOWS /W3 /GR /EHsc /WX" -DCMAKE_C_FLAGS="/DWIN32 /D_WINDOWS /W3 /WX" ..

    "%programfiles(x86)%\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\amd64\MsBuild.exe" /nologo /m:2 /p:Configuration=RelWithDebInfo /p:Platform="X64" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" "TrinityCore.sln"

    cd bin\RelWithDebInfo\

    copy "C:\Program Files\MySQL\MySQL Server 5.7\lib\libmysql.dll" libmysql.dll

    copy "%OPENSSL_ROOT_DIR%\ssleay32.dll" ssleay32.dll

    copy "%OPENSSL_ROOT_DIR%\libeay32.dll" libeay32.dll


test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: build\bin\RelWithDebInfo\
  name: ElunaTrinityWotlkWin64VS2019
