
# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# Stabilize first
pull_requests:
  do_not_increment_build_number: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# environment
environment:
  CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
  BOOST_ROOT: C:\Libraries\boost_1_67_0
  BOOST_INCLUDEDIR: C:\Libraries\boost_1_67_0\boost
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_67_0\lib64-msvc-14.1
  OPENSSL_ROOT_DIR: C:\OpenSSL-Win64

# clone directory
clone_folder: c:\projects\ElunaTrinityWotlk

# set clone depth
clone_depth: 1                      # clone entire repository history if not defined

# fetch repository as zip archive
shallow_clone: true

# clone script
clone_script:
  cmd: git clone -q --depth=1 --branch=master https://github.com/RedSkull-666/ElunaTrinityWotlk.git C:\projects\ElunaTrinityWotlk

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# build Configuration, i.e. Debug, Release, etc.
configuration: RelWithDebInfo

# Build settings, not to be confused with "before_build" and "after_build".
# "project" is relative to the original build directory and not influenced by directory changes in "before_build".
build:
  parallel: true                  # enable MSBuild parallel builds
  project: TrinityCore.sln        # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: minimal

# scripts to run before build
before_build:
  - git config user.email "appveyor@build.bot" && git config user.name "AppVeyor"
  - git tag -a -m "AppVeyor build" init
  - md build && cd build
  - cmake -G"Visual Studio 15 2017 Win64" -DSCRIPTS=dynamic -DTOOLS=True -DCMAKE_CXX_FLAGS=" /DWIN32 /D_WINDOWS /W3 /GR /EHsc /WX" -DCMAKE_C_FLAGS="/DWIN32 /D_WINDOWS /W3 /WX" ..

# build scripts
build_script:
  - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64\MsBuild.exe" /nologo /m:2 /p:Configuration=RelWithDebInfo /p:Platform="X64" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" "TrinityCore.sln"

# scripts to run after build (working directory and environment changes are persisted from the previous steps)
after_build:
  - cd bin\RelWithDebInfo\
  - copy "C:\Program Files\MySQL\MySQL Server 5.7\lib\libmysql.dll" libmysql.dll
  - copy "%OPENSSL_ROOT_DIR%\ssleay32.dll" ssleay32.dll
  - copy "%OPENSSL_ROOT_DIR%\libeay32.dll" libeay32.dll

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  # pushing a single file
  path: build\bin\RelWithDebInfo\
  name: ElunaTrinityWotlkWin64VS2017
